### ISSUE TITLE
[BUG] TOC page missed in generated PDF file in ubuntu20.04.

### ISSUE THREAD

**Issue by ZhenshengLee** [xiaoweiChen/Software-Architecture-with-Cpp#1]
### env

- ubuntu20.04-latest

### step to reproduce

```sh
sudo apt install texlive-full -y
sudo apt-get install texlive-xetex latex-cjk-all
sudo apt-get install texmaker
```

```sh
xelatex ./Software-Architecture-with-C++.tex
```

### behavior

```sh
Package hyperref Warning: old toc file detected, not used; run LaTeX again.
```

the toc page missed, while the toc bookmarks of pdf appear normally.

### expected

TOC showing in the pdf file.

**Comment by xiaoweiChen** [comment]
Could you generate the PDF under Windows? 
I just generate the PDF on Windows, not test other OS. 
Base on Readme: 
https://www.cnblogs.com/1625--H/p/11524968.html

Or vscode https://blog.csdn.net/Ruins_LEE/article/details/123555016

In TeXstudio, I see the generation command line is 
```
xelatex.exe -synctex=1 -interaction=nonstopmode "C++-Templates-The-Complete-Guide".tex
```
You can try this line under your Linux environment.

**Comment by ZhenshengLee** [comment]
Thank you very much! @xiaoweiChen 

this command works perfect!

```
xelatex -synctex=1 -interaction=nonstopmode ./Software-Architecture-with-C++.tex
```

Closing this.

**Comment by xiaoweiChen** [comment]
我这边在docker里面用官方的ubuntu20.04的镜像，按照你的复现步骤尝试了一下。
并没有出现“TOC没有的情况”，也许你那边再次运行下`xelatex ./Software-Architecture-with-C++.tex`就好了。

第一次运行
```
xelatex ./Software-Architecture-with-C++.tex
```
后生成的PDF没有封面。
再运行一下，生成的PDF封面就出来了。

=============================

很高兴看到你那边已经解决了 :)
